/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef CBPDF
#define CBPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class CBPdf : public RooAbsPdf {
public:
  CBPdf() {} ;
  CBPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _A,
	      RooAbsReal& _B,
        RooAbsReal& _C,
        RooAbsReal& _D);
  CBPdf(const CBPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new CBPdf(*this,newname); }
  inline virtual ~CBPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy C ;
  RooRealProxy D ;

  Double_t evaluate() const ;

private:

  ClassDef(CBPdf,1) // Your description goes here...
};

#endif
