/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef NA60PDF
#define NA60PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class NA60Pdf : public RooAbsPdf {
public:
  NA60Pdf() {} ;
  NA60Pdf(const char *name, const char *title,
	     
          RooAbsReal& _x,
          RooAbsReal& _xmean,
          RooAbsReal& _sigma,
	        RooAbsReal& _alphaleft,
	        RooAbsReal& _p1left,
          RooAbsReal& _p2left,
          RooAbsReal& _p3left,
          RooAbsReal& _alpharight,
          RooAbsReal& _p1right,
          RooAbsReal& _p2right,
          RooAbsReal& _p3right);

  NA60Pdf(const NA60Pdf& other, const char* name=0);
  virtual TObject* clone(const char* newname) const { return new NA60Pdf(*this,newname); }
  inline virtual ~NA60Pdf() { }

protected:
  RooRealProxy x ;
  RooRealProxy xmean ;
  RooRealProxy sigma ;
  RooRealProxy alphaleft ;
  RooRealProxy p1left ;
  RooRealProxy p2left ;
  RooRealProxy p3left ;
  RooRealProxy alpharight ;
  RooRealProxy p1right ;
  RooRealProxy p2right ;
  RooRealProxy p3right ;

  Double_t evaluate() const ;

private:

  ClassDef(NA60Pdf,1) // Your description goes here...
};

#endif
