/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "PtPdf.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

ClassImp(PtPdf);

 PtPdf::PtPdf(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _B,
                        RooAbsReal& _n1,
                        RooAbsReal& _n2) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   B("B","B",this,_B),
   n1("n1","n1",this,_n1),
   n2("n2","n2",this,_n2)
 {
 }


 PtPdf::PtPdf(const PtPdf& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   B("B",this,other.B),
   n1("n1",this,other.n1),
   n2("n2",this,other.n2)
 {
 }



 Double_t PtPdf::evaluate() const
 {
   return x/TMath::Power(1 + TMath::Power(x/B,n1),n2);
 }
