/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef PTPDF
#define PTPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class PtPdf : public RooAbsPdf {
public:
  PtPdf() {} ;
  PtPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _B,
        RooAbsReal& _n1,
        RooAbsReal& _n2);
  PtPdf(const PtPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new PtPdf(*this,newname); }
  inline virtual ~PtPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy B ;
  RooRealProxy n1 ;
  RooRealProxy n2 ;

  Double_t evaluate() const ;

private:

  ClassDef(PtPdf,1) // Your description goes here...
};

#endif
