/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "ResPdf.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

ClassImp(ResPdf);

 ResPdf::ResPdf(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _alpha,
                        RooAbsReal& _lambda) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   alpha("alpha","alpha",this,_alpha),
   lambda("lambda","lambda",this,_lambda)
 {
 }


 ResPdf::ResPdf(const ResPdf& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   alpha("alpha",this,other.alpha),
   lambda("lambda",this,other.lambda)
 {
 }



 Double_t ResPdf::evaluate() const
 {
   double val = 0;
   if (TMath::Abs(x) < alpha) {
     val = (lambda - 1.) / (2. * alpha * lambda);
   }
   if (TMath::Abs(x) > alpha) {
     val = (lambda - 1.) / (2. * alpha * lambda) * alpha * TMath::Power(TMath::Abs(x),-lambda);
   }
   return val;
 }
