/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RESPDF
#define RESPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class ResPdf : public RooAbsPdf {
public:
  ResPdf() {} ;
  ResPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _alpha,
        RooAbsReal& _lambda);
  ResPdf(const ResPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ResPdf(*this,newname); }
  inline virtual ~ResPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy alpha ;
  RooRealProxy lambda ;

  Double_t evaluate() const ;

private:

  ClassDef(ResPdf,1) // Your description goes here...
};

#endif
